language: ruby

rvm:
  - 2.1.1

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle install
  - npm install -g grunt-cli
  - npm install

addons:
  firefox: "35.0"

script: grunt build